# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9pHz6ztm1v8Bs5NjRVbnFwGalyeyT6W
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/student-mat.csv", sep=";")
print("Data loaded sucessfully!")

print(data.head())
print("\nDataset Info:")
print(data.info())



print ("\nmissing value:")
print(data.isnull().sum())

data = data.drop_duplicates()

average_score = data['G3'].mean()
print(f"\nAverage Math score (G3): {average_score:.2f}")

students_above_15 = len(data[data['G3'] > 15])
print(f"Number of students scoring above 15: {students_above_15}")

correlation = data['studytime'].corr(data['G3'])
print(f"correlation between study time and final grade: {correlation:.2f}")

average_grade_by_gender = data.groupby('sex')['G3'].mean()
print("\nAverage grade by gender:")
print(average_grade_by_gender)

plt.figure(figsize=(8, 5))
plt.hist(data['G3'], bins=10, color='skyblue', edgecolor='black')
plt.title("Distribution of Final Grades (G3)")
plt.xlabel("Final Grade")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8, 5))

sns.scatterplot(data=data, x='studytime', y='G3', hue='sex')

plt.title("Study Time vs Final Grade")

plt.xlabel("Study Time (hours)")

plt.ylabel("Final Grade")

plt.legend(title="Gender")

plt.show()



plt.figure(figsize=(8, 5))

average_grade_by_gender.plot(kind='bar', color=['blue', 'pink'])

plt.title("Average Final Grade by Gender")

plt.ylabel("Average Final Grade")

plt.xlabel("Gender")

plt.xticks(rotation=0)

plt.show()
