# -*- coding: utf-8 -*-
"""TASK4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FBun3lSVL1RQKWNC1xTT4H0z-XATjgB
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

import pandas as pd

file_path = "/content/sample_data/house_prices_dataset.csv"
df = pd.read_csv(file_path)

print(df.head())

df_encoded = pd.get_dummies(df, columns=['mainroad', 'guestroom', 'basement',
                                          'hotwaterheating', 'airconditioning',
                                          'prefarea', 'furnishingstatus'], drop_first=True)

print(df_encoded.head())

X = df_encoded.drop(columns=['price'])
y = df_encoded['price']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: ₹{mae:,.2f}")
print(f"R² Score: {r2:.2f}")

print("\nEnter House Details:")

area = float(input("Enter Area (sq ft): "))
bedrooms = int(input("Enter Number of Bedrooms: "))
bathrooms = int(input("Enter Number of Bathrooms: "))
stories = int(input("Enter Number of Stories: "))
parking = int(input("Enter Number of Parking Spaces: "))

mainroad = int(input("Is it on the Main Road? (Yes=1, No=0): "))
guestroom = int(input("Does it have a Guest Room? (Yes=1, No=0): "))
basement = int(input("Does it have a Basement? (Yes=1, No=0): "))
hotwaterheating = int(input("Does it have Hot Water Heating? (Yes=1, No=0): "))
airconditioning = int(input("Does it have Air Conditioning? (Yes=1, No=0): "))
prefarea = int(input("Is it in a Preferred Area? (Yes=1, No=0): "))

furnishing_status = input("Furnishing Status (furnished / semi-furnished / unfurnished): ").strip().lower()
furnished = 1 if furnishing_status == "furnished" else 0
semi_furnished = 1 if furnishing_status == "semi-furnished" else 0
unfurnished = 1 if furnishing_status == "unfurnished" else 0

new_house = pd.DataFrame({
    'area': [area],
    'bedrooms': [bedrooms],
    'bathrooms': [bathrooms],
    'stories': [stories],
    'parking': [parking],
    'mainroad_yes': [mainroad],
    'guestroom_yes': [guestroom],
    'basement_yes': [basement],
    'hotwaterheating_yes': [hotwaterheating],
    'airconditioning_yes': [airconditioning],
    'prefarea_yes': [prefarea],
    'furnishingstatus_semi-furnished': [semi_furnished],
    'furnishingstatus_unfurnished': [unfurnished]
})

predicted_price = model.predict(new_house)
print(f"\nPredicted House Price: ₹{predicted_price[0]:,.2f}")